@echo off
sc start spectrum >nul 2>&1
sc start NdisImPlatform >nul 2>&1
sc start gpsvc >nul 2>&1
sc start TPM >nul 2>&1
sc start ndfltr >nul 2>&1
sc start TPVCGateway >nul 2>&1
sc start nvstor >nul 2>&1
sc start mvumis >nul 2>&1
sc start nvdimmn >nul 2>&1
sc start smphost >nul 2>&1
sc start stexstor >nul 2>&1
sc start TieringEngineService >nul 2>&1
sc start MSiSCSI >nul 2>&1
sc start MSPQM >nul 2>&1
sc start stornvme >nul 2>&1
sc start terminpt >nul 2>&1
sc start NetAdapterCx >nul 2>&1
sc start Modem >nul 2>&1
sc start UdeCx >nul 2>&1
sc start UcmTcpciCx0101 >nul 2>&1
sc start UcmCx0101 >nul 2>&1
sc start PerfHost >nul 2>&1
sc start storvsc >nul 2>&1
sc start msgpiowin32 >nul 2>&1
sc start mshidkmdf >nul 2>&1
sc start UEFI >nul 2>&1
sc start MsBridge >nul 2>&1
sc start mshidumdf >nul 2>&1
sc start mlx4_bus >nul 2>&1
sc start DoSvc >nul 2>&1
sc start megasas2i >nul 2>&1
sc start pla >nul 2>&1
sc start percsas2i >nul 2>&1
sc start mausbip >nul 2>&1
sc start nvraid >nul 2>&1
sc start ufxsynopsys >nul 2>&1
sc start Parport >nul 2>&1
sc start LSI_SAS3i >nul 2>&1
sc start LSI_SAS2i >nul 2>&1
sc start UfxChipidea >nul 2>&1
sc start MSKSSRV >nul 2>&1
sc start LSI_SSS >nul 2>&1
sc start UmPass >nul 2>&1
sc start TPAutoConnSvc >nul 2>&1
sc start storufs >nul 2>&1
sc start TermService >nul 2>&1
sc start Synth3dVsc >nul 2>&1
sc start UrsChipidea >nul 2>&1
sc start usbser >nul 2>&1
sc start usbprint >nul 2>&1
sc start kbdhid >nul 2>&1
sc start pciide >nul 2>&1
sc start AppXSvc >nul 2>&1
sc start netvsc >nul 2>&1
sc start isapnp >nul 2>&1
sc start UrsSynopsys >nul 2>&1
sc start KtmRm >nul 2>&1
sc start UrsCx01000 >nul 2>&1
sc start USBSTOR >nul 2>&1
sc start irmon >nul 2>&1
sc start irda >nul 2>&1
sc start IRENUM >nul 2>&1
sc start SpatialGraphFilter >nul 2>&1
sc start tsusbhub >nul 2>&1
sc start vds >nul 2>&1
sc start IndirectKmd >nul 2>&1
sc start vhdmp >nul 2>&1
sc start vhf >nul 2>&1
sc start iai2c >nul 2>&1
sc start hyperkbd >nul 2>&1
sc start iaLPSS2i_I2C >nul 2>&1
sc start iaStorV >nul 2>&1
sc start iaStorAV >nul 2>&1
sc start iaLPSSi_I2C >nul 2>&1
sc start iaLPSSi_GPIO >nul 2>&1
sc start iaLPSS2i_I2C_BXT_P >nul 2>&1
sc start iaLPSS2i_GPIO2_BXT_P >nul 2>&1
sc start iaLPSS2i_GPIO2 >nul 2>&1
sc start VMBusHID >nul 2>&1
sc start SpbCx >nul 2>&1
sc start storflt >nul 2>&1
sc start hvservice >nul 2>&1
sc start HomeGroupProvider >nul 2>&1
sc start HomeGroupListener >nul 2>&1
sc start hidinterrupt >nul 2>&1
sc start hidi2c >nul 2>&1
sc start HidBth >nul 2>&1
sc start HidBatt >nul 2>&1
sc start HidIr >nul 2>&1
sc start hidserv >nul 2>&1
sc start genericusbfn >nul 2>&1
sc start FsDepends >nul 2>&1
sc start vmicvmsession >nul 2>&1
sc start TabletInputService >nul 2>&1
sc start wuauserv >nul 2>&1
sc start flpydisk >nul 2>&1
sc start vmvss >nul 2>&1
sc start HpSAMD >nul 2>&1
sc start FDResPub >nul 2>&1
sc start fdc >nul 2>&1
sc start fdPHost >nul 2>&1
sc start exfat >nul 2>&1
sc start vsmraid >nul 2>&1
sc start TapiSrv >nul 2>&1
sc start ErrDev >nul 2>&1
sc start NdisCap >nul 2>&1
sc start EntAppSvc >nul 2>&1
sc start VSTXRAID >nul 2>&1
sc start EhStorTcgDrv >nul 2>&1
sc start pmem >nul 2>&1
sc start PNRPAutoReg >nul 2>&1
sc start ebdrv >nul 2>&1
sc start EFS >nul 2>&1
sc start WacomPen >nul 2>&1
sc start W32Time >nul 2>&1
sc start DsSvc >nul 2>&1
sc start drmkaud >nul 2>&1
sc start NaturalAuthentication >nul 2>&1
sc start vwifibus >nul 2>&1
sc start IpFilterDriver >nul 2>&1
sc start dot3svc >nul 2>&1
sc start EapHost >nul 2>&1
sc start TsUsbFlt >nul 2>&1
sc start MSTEE >nul 2>&1
sc start dmvsc >nul 2>&1
sc start MTConfig >nul 2>&1
sc start DmEnrollmentSvc >nul 2>&1
sc start percsas3i >nul 2>&1
sc start MsSecFlt >nul 2>&1
sc start wcnfs >nul 2>&1
sc start wcncsvc >nul 2>&1
sc start GPIOClx0101 >nul 2>&1
sc start DevicesFlowUserSvc_41ec6 >nul 2>&1
sc start MSPCLOCK >nul 2>&1
sc start pcmcia >nul 2>&1
sc start TsUsbGD >nul 2>&1
sc start p2psvc >nul 2>&1
sc start CscService >nul 2>&1
sc start WebClient >nul 2>&1
sc start MRxDAV >nul 2>&1
sc start Wecsvc >nul 2>&1
sc start wercplsupport >nul 2>&1
sc start fastfat >nul 2>&1
sc start WinMad >nul 2>&1
sc start WIMMount >nul 2>&1
sc start circlass >nul 2>&1
sc start cht4vbd >nul 2>&1
sc start cht4iscsi >nul 2>&1
sc start UASPStor >nul 2>&1
sc start tunnel >nul 2>&1
sc start CertPropSvc >nul 2>&1
sc start WinRM >nul 2>&1
sc start CapImg >nul 2>&1
sc start WinVerbs >nul 2>&1
sc start ibbus >nul 2>&1
sc start buttonconverter >nul 2>&1
sc start BTHMODEM >nul 2>&1
sc start CAD >nul 2>&1
sc start WINUSB >nul 2>&1
sc start bthhfhid >nul 2>&1
sc start BthHFEnum >nul 2>&1
sc start BthAvrcpTg >nul 2>&1
sc start BthHFSrv >nul 2>&1
sc start bthserv >nul 2>&1
sc start megasas >nul 2>&1
sc start WlanSvc >nul 2>&1
sc start NativeWifiP >nul 2>&1
sc start diagnosticshub.standardcollector.service >nul 2>&1
sc start megasr >nul 2>&1
sc start WmiAcpi >nul 2>&1
sc start VerifierExt >nul 2>&1
sc start wmiApSrv >nul 2>&1
sc start bcmfn2 >nul 2>&1
sc start mausbhost >nul 2>&1
sc start WMPNetworkSvc >nul 2>&1
sc start b06bdrv >nul 2>&1
sc start workfolderssvc >nul 2>&1
sc start Ufx01000 >nul 2>&1
sc start NetTcpPortSharing >nul 2>&1
sc start arcsas >nul 2>&1
sc start iorate >nul 2>&1
sc start SENS >nul 2>&1
sc start AppvVemgr >nul 2>&1
sc start AppvStrm >nul 2>&1
sc start Netman >nul 2>&1
sc start AppMgmt >nul 2>&1
sc start applockerfltr >nul 2>&1
sc start WwanSvc >nul 2>&1
sc start AppID >nul 2>&1
sc start amdsbs >nul 2>&1
sc start amdsata >nul 2>&1
sc start AppIDSvc >nul 2>&1
sc start amdxata >nul 2>&1
sc start ALG >nul 2>&1
sc start UmRdpService >nul 2>&1
sc start Filetrace >nul 2>&1
sc start acpipagr >nul 2>&1
sc start AcpiDev >nul 2>&1
sc start upnphost >nul 2>&1
sc start ADP80XX >nul 2>&1
sc start acpitime >nul 2>&1
sc start AcpiPmi >nul 2>&1
sc start xboxgip >nul 2>&1
sc start 1394ohci >nul 2>&1
sc start XboxGipSvc >nul 2>&1
sc start 3ware >nul 2>&1
sc start SNMPTRAP >nul 2>&1
sc start usbohci >nul 2>&1
sc start Ndisuio >nul 2>&1
sc start RasAuto >nul 2>&1
sc start usbcir >nul 2>&1
sc start iScsiPrt >nul 2>&1
sc start SiSRaid4 >nul 2>&1
sc start QWAVEdrv >nul 2>&1
sc start QWAVE >nul 2>&1
sc start RasAcd >nul 2>&1
sc start SstpSvc >nul 2>&1
sc start NdisWan >nul 2>&1
sc start Rasl2tp >nul 2>&1
sc start PptpMiniport >nul 2>&1
sc start wanarp >nul 2>&1
sc start NdisTapi >nul 2>&1
sc start ndproxy >nul 2>&1
sc start RasAgileVpn >nul 2>&1
sc start RasSstp >nul 2>&1
sc start RasPppoe >nul 2>&1
sc start SiSRaid2 >nul 2>&1
sc start RDPDR >nul 2>&1
sc start RdpVideoMiniport >nul 2>&1
sc start ReFSv1 >nul 2>&1
sc start ReFS >nul 2>&1
sc start IPMIDRV >nul 2>&1
sc start RmSvc >nul 2>&1
sc start rpcapd >nul 2>&1
sc start sfloppy >nul 2>&1
sc start RpcLocator >nul 2>&1
sc start sbp2port >nul 2>&1
sc start SerCx2 >nul 2>&1
sc start s3cap >nul 2>&1
sc start sermouse >nul 2>&1
sc start SessionEnv >nul 2>&1
sc start scfilter >nul 2>&1
sc start RasMan >nul 2>&1
sc start SDFRd >nul 2>&1
sc start sdbus >nul 2>&1
sc start sdstor >nul 2>&1
sc start SDRSVC >nul 2>&1
sc start seclogon >nul 2>&1
sc start SerCx >nul 2>&1
sc start scmbus >nul 2>&1
sc start PNRPsvc >nul 2>&1
sc start xinputhid >nul 2>&1
sc start WPDBusEnum >nul 2>&1
sc start SensorService >nul 2>&1
sc start SensorsHIDClassDriver >nul 2>&1
sc start SensrSvc >nul 2>&1
sc start Schedule >nul 2>&1
sc start SamSs >nul 2>&1
sc start Serenum >nul 2>&1
sc start Serial >nul 2>&1
sc start rspndr >nul 2>&1
sc start RpcSs >nul 2>&1
sc start RpcEptMapper >nul 2>&1
sc start rdyboost >nul 2>&1
sc start ShellHWDetection >nul 2>&1
sc start rdpbus >nul 2>&1
sc start rdbss >nul 2>&1
sc start Psched >nul 2>&1
sc start ProfSvc >nul 2>&1
sc start Power >nul 2>&1
sc start PolicyAgent >nul 2>&1
sc start spaceport >nul 2>&1
sc start PlugPlay >nul 2>&1
sc start PimIndexMaintenanceSvc_41ec6 >nul 2>&1
sc start PEAUTH >nul 2>&1
sc start Spooler >nul 2>&1
sc start pdc >nul 2>&1
sc start srv >nul 2>&1
sc start srv2 >nul 2>&1
sc start srvnet >nul 2>&1
sc start pcw >nul 2>&1
sc start pci >nul 2>&1
sc start StateRepository >nul 2>&1
sc start PcaSvc >nul 2>&1
sc start partmgr >nul 2>&1
sc start storahci >nul 2>&1
sc start OneSyncSvc_41ec6 >nul 2>&1
sc start Null >nul 2>&1
sc start storqosflt >nul 2>&1
sc start StorSvc >nul 2>&1
sc start NTFS >nul 2>&1
sc start nsiproxy >nul 2>&1
sc start nsi >nul 2>&1
sc start swenum >nul 2>&1
sc start npsvctrig >nul 2>&1
sc start Npfs >nul 2>&1
sc start SysMain >nul 2>&1
sc start SystemEventsBroker >nul 2>&1
sc start NPF >nul 2>&1
sc start NlaSvc >nul 2>&1
sc start Tcpip >nul 2>&1
sc start netprofm >nul 2>&1
sc start tcpipreg >nul 2>&1
sc start tdx >nul 2>&1
sc start NetBT >nul 2>&1
sc start NetBIOS >nul 2>&1
sc start Themes >nul 2>&1
sc start Ndu >nul 2>&1
sc start tiledatamodelsvc >nul 2>&1
sc start TimeBrokerSvc >nul 2>&1
sc start TokenBroker >nul 2>&1
sc start NdisVirtualBus >nul 2>&1
sc start NDIS >nul 2>&1
sc start NcbService >nul 2>&1
sc start TrkWks >nul 2>&1
sc start Mup >nul 2>&1
sc start mssmbios >nul 2>&1
sc start MsLldp >nul 2>&1
sc start msisadrv >nul 2>&1
sc start Msfs >nul 2>&1
sc start MSDTC >nul 2>&1
sc start mrxsmb20 >nul 2>&1
sc start mrxsmb10 >nul 2>&1
sc start mrxsmb >nul 2>&1
sc start MpsSvc >nul 2>&1
sc start Ucx01000 >nul 2>&1
sc start mpsdrv >nul 2>&1
sc start mountmgr >nul 2>&1
sc start mouhid >nul 2>&1
sc start mouclass >nul 2>&1
sc start monitor >nul 2>&1
sc start MMCSS >nul 2>&1
sc start luafv >nul 2>&1
sc start LSM >nul 2>&1
sc start LSI_SAS >nul 2>&1
sc start umbus >nul 2>&1
sc start lmhosts >nul 2>&1
sc start lltdio >nul 2>&1
sc start LicenseManager >nul 2>&1
sc start UnistoreSvc_41ec6 >nul 2>&1
sc start lfsvc >nul 2>&1
sc start LanmanWorkstation >nul 2>&1
sc start LanmanServer >nul 2>&1
sc start ksthunk >nul 2>&1
sc start usbccgp >nul 2>&1
sc start KSecPkg >nul 2>&1
sc start usbehci >nul 2>&1
sc start usbhub >nul 2>&1
sc start USBHUB3 >nul 2>&1
sc start KSecDD >nul 2>&1
sc start USBPcap >nul 2>&1
sc start KProcessHacker3 >nul 2>&1
sc start KeyIso >nul 2>&1
sc start kdnic >nul 2>&1
sc start usbuhci >nul 2>&1
sc start USBXHCI >nul 2>&1
sc start kbdclass >nul 2>&1
sc start UserDataSvc_41ec6 >nul 2>&1
sc start UserManager >nul 2>&1
sc start iphlpsvc >nul 2>&1
sc start VaultSvc >nul 2>&1
sc start vdrvroot >nul 2>&1
sc start intelppm >nul 2>&1
sc start VGAuthService >nul 2>&1
sc start intelpep >nul 2>&1
sc start intelide >nul 2>&1
sc start vm3dmp >nul 2>&1
sc start IKEEXT >nul 2>&1
sc start i8042prt >nul 2>&1
sc start vmci >nul 2>&1
sc start HTTP >nul 2>&1
sc start vmhgfs >nul 2>&1
sc start HidUsb >nul 2>&1
sc start HDAudBus >nul 2>&1
sc start HdAudAddService >nul 2>&1
sc start GpuEnergyDrv >nul 2>&1
sc start wdiwifi >nul 2>&1
sc start gencounter >nul 2>&1
sc start fvevol >nul 2>&1
sc start FontCache >nul 2>&1
sc start VMMemCtl >nul 2>&1
sc start vmmouse >nul 2>&1
sc start vmrawdsk >nul 2>&1
sc start VMTools >nul 2>&1
sc start vmusbmouse >nul 2>&1
sc start FltMgr >nul 2>&1
sc start VMware Physical Disk Helper Service >nul 2>&1
sc start FileInfo >nul 2>&1
sc start VMwareCAFManagementAgentHost >nul 2>&1
sc start volmgr >nul 2>&1
sc start volmgrx >nul 2>&1
sc start volsnap >nul 2>&1
sc start volume >nul 2>&1
sc start FileCrypt >nul 2>&1
sc start EventSystem >nul 2>&1
sc start vsock >nul 2>&1
sc start EventLog >nul 2>&1
sc start EhStorClass >nul 2>&1
sc start e1iexpress >nul 2>&1
sc start vwififlt >nul 2>&1
sc start DXGKrnl >nul 2>&1
sc start DusmSvc >nul 2>&1
sc start DsmSvc >nul 2>&1
sc start DPS >nul 2>&1
sc start Dnscache >nul 2>&1
sc start Disk >nul 2>&1
sc start DiagTrack >nul 2>&1
sc start wcifs >nul 2>&1
sc start Wcmsvc >nul 2>&1
sc start Dhcp >nul 2>&1
sc start Dfsc >nul 2>&1
sc start DcomLaunch >nul 2>&1
sc start Wdf01000 >nul 2>&1
sc start WdFilter >nul 2>&1
sc start WdiServiceHost >nul 2>&1
sc start WdiSystemHost >nul 2>&1
sc start CSC >nul 2>&1
sc start WdNisDrv >nul 2>&1
sc start WdNisSvc >nul 2>&1
sc start CryptSvc >nul 2>&1
sc start CoreMessagingRegistrar >nul 2>&1
sc start condrv >nul 2>&1
sc start COMSysApp >nul 2>&1
sc start p2pimsvc >nul 2>&1
sc start CompositeBus >nul 2>&1
sc start WFPLWFS >nul 2>&1
sc start CNG >nul 2>&1
sc start CmBatt >nul 2>&1
sc start WinDefend >nul 2>&1
sc start WindowsTrustedRT >nul 2>&1
sc start WindowsTrustedRTProxy >nul 2>&1
sc start WinHttpAutoProxySvc >nul 2>&1
sc start clreg >nul 2>&1
sc start Winmgmt >nul 2>&1
sc start CLFS >nul 2>&1
sc start cdrom >nul 2>&1
sc start CDPUserSvc_41ec6 >nul 2>&1
sc start CDPSvc >nul 2>&1
sc start Browser >nul 2>&1
sc start BrokerInfrastructure >nul 2>&1
sc start SSDPSRV >nul 2>&1
sc start bowser >nul 2>&1
sc start BFE >nul 2>&1
sc start Beep >nul 2>&1
sc start BasicRender >nul 2>&1
sc start Wof >nul 2>&1
sc start BasicDisplay >nul 2>&1
sc start Audiosrv >nul 2>&1
sc start AudioEndpointBuilder >nul 2>&1
sc start WpnService >nul 2>&1
sc start atapi >nul 2>&1
sc start WpnUserService_41ec6 >nul 2>&1
sc start ws2ifsl >nul 2>&1
sc start wscsvc >nul 2>&1
sc start WSearch >nul 2>&1
sc start SecurityHealthService >nul 2>&1
sc start WudfPf >nul 2>&1
sc start WUDFRd >nul 2>&1
sc start wudfsvc >nul 2>&1
sc start Appinfo >nul 2>&1
sc start ahcache >nul 2>&1
sc start WpdUpFltr >nul 2>&1
sc start AFD >nul 2>&1
sc start acpiex >nul 2>&1
sc start ACPI >nul 2>&1
sc start XboxNetApiSvc >nul 2>&1
sc start AsyncMac >nul 2>&1
sc start AppvVfs >nul 2>&1
echo All Windows services are fixed.
echo Don't forget to fix ur mood too :)
echo Be Happy and if u want it, GET IT !!
pause
@echo on